#!/bin/sh
# This script is only meant to be executed in the context of these dotfiles

cd "$(dirname "${BASH_SOURCE}")";

rsync --exclude ".git/" \
  --exclude ".DS_Store" \
  --exclude ".osx" \
  --exclude "install" \
  --exclude "README.md" \
  --exclude "LICENSE-MIT.txt" \
  --exclude "fs_shortcuts_files" \
  -avh --no-perms . ~;
  source ~/.bash_profile;

cd -

./fs_shortcuts_files
