#!/bin/sh

curl -X PUT localhost:9200/user/user/_mapping  \
  -H "Content-Type: application/json" \
  -d @- <<HEREDOC
{
    "properties": {
        "photos_length": {
            "type": "integer"
        }
    }
}
HEREDOC
