#!/bin/sh

curl -X PUT prod.hostname.com/user/user/_mapping  \
  -H "Content-Type: application/json" \
  -d @- <<HEREDOC
{
    "properties": {
        "active_party_id": {
            "type": "keyword"
        }
    }
}
HEREDOC
