#!/bin/sh

max_size="5000"

exp="$1"
[ -z "$exp" ] && exit
shift

dirs="$@"
[ -z "$dirs" ] && dirs=~/dev

ag -l --follow --hidden --ignore "*.git*" --ignore "*node_modules*" $exp $dirs 2>/dev/null \
  | xargs -r du \
  | awk -v max_size="$max_size" '{ if ($1 < max_size) { print $2 } }'
