#!/bin/sh

curl -X PUT localhost:9200/party  \
  -H 'Content-Type: application/json' \
  -d @- <<HEREDOC
{
    "mappings": {
        "party": {
            "properties": {
                "groups": {
                    "type": "nested",
                    "properties": {
                        "_id": {
                            "type": "keyword"
                        }
                    }
                },
                "age_range": {
                    "type": "integer_range"
                },
                "rating": {
                    "type": "integer_range"
                },
                "location": {
                    "type": "geo_point"
                },
                "start_time": {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "end_time": {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "time_frame": {
                    "type": "date_range",
                    "format": "epoch_millis"
                }
            }
        }
    }
}
HEREDOC

curl -X PUT localhost:9200/feedback  \
  -H 'Content-Type: application/json' \
  -d @- <<HEREDOC
{
    "mappings": {
        "feedback": {
            "properties": {
                "rating": {
                    "type": "integer"
                },
                "type": {
                    "type": "keyword"
                },
                "tags": {
                    "type": "keyword"
                },
                "create_time": {
                    "type": "date",
                    "format": "epoch_millis"
                }
            }
        }
    }
}
HEREDOC

curl -X PUT localhost:9200/user  \
  -H 'Content-Type: application/json' \
  -d @- <<HEREDOC
{
    "mappings": {
        "user": {
            "properties": {
                "name": {
                    "type": "text"
                },
                "gender": {
                    "type": "keyword"
                },
                "clean_phone_number": {
                    "type": "text"
                },
                "groups": {
                    "type": "nested",
                    "properties": {
                        "_id": {
                            "type": "keyword"
                        }
                    }
                },
                "instagram_handle": {
                    "type": "text"
                },
                "status": {
                    "type": "keyword"
                },
                "birthday": {
                    "type": "text"
                },
                "birthdate": {
                    "type": "date"
                },
                "rating": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "location": {
                    "type": "geo_point"
                },
                "update_time": {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "create_time": {
                    "type": "date",
                    "format": "epoch_millis"
                }
            }
        }
    }
}
HEREDOC
