#!/bin/sh
# Qualifying publish of dandy modules
# --check outputs the modules that need publish without publishing

check=""
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -c|--check) check="1"; shift
  esac
done

dandymods=$(find $DANDY_PATH -maxdepth 1 -mindepth 1 -type d)
ignoremodsfile="$HOME/.data/ddy-ignore-publish-modules.txt"
ignoremods=$(cat "$ignoremodsfile")

for mod in $dandymods; do
  grep -Fxq "$(basename $mod)" "$ignoremodsfile" && continue
  cd "$mod"
  head_commit_msg=$(git log -1 --pretty=%B | tr -d '[[:space:]]')
  pkg_version=$(cat package.json \
    | grep version \
    | head -1 \
    | awk -F: '{ print $2 }' \
    | sed 's/[",]//g' \
    | tr -d '[[:space:]]'
  )
  [ "$head_commit_msg" == "$pkg_version" ] && continue
  echo $mod
  [ -n "$check" ] && continue
  npm version patch
  npm publish &>/dev/null &
  git push &>/dev/null &
done
