#!/bin/sh
# Connects to wifi

nmcli radio wifi on

chosen=$(
  nmcli -t device wifi list \
    | cut -d ':' -f "2,5,7" \
    | awk -F ":" '$1{print $1 " - " $3 " " $2}' \
    | dmenu -i -l 20 -fn Monospace-10 \
    | awk -F " - " '{print $1}'
)

[ "$chosen" != "" ] || exit

nmcli device wifi connect "$chosen" --ask
