#!/bin/sh

find ~/code \( \
  -name ".git" -o \
  -name ".npm" -o \
  -name "node_modules" -o \
  -name ".cache" -o \
  -name "go" -o \
  -name "vendor" -o \
  -name "pkg" \
\) -prune -o -type d -print
