#!/bin/sh
# The real git s

dir="$1"
[ -z "$dir" ] && dir="$(pwd)"

pretty_dir="$(echo "$dir" | sed s:^$HOME:~:g)"

cur_branch="$(git branch | grep \* | cut -d ' ' -f2)"
tracking_branch="$(git rev-parse --abbrev-ref "$cur_branch@{upstream}" 2>/dev/null)"

[ -z "$tracking_branch" ] || read -r cur_branch_ct tracking_branch_ct <<< $(
  git-compare-count "$dir" "$cur_branch" "$tracking_branch"
)

RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

DELIM=" "

out=""
out+="$BLUE$pretty_dir$NC"
out+="$DELIM"
out+="$GREEN$cur_branch$NC"
out+="$DELIM"
[ -z "$tracking_branch" ] || out+="$RED$tracking_branch$NC"
out+="$DELIM"
[ "$cur_branch_ct" != "0" ] && out+="+$cur_branch_ct"
out+="$DELIM"
[ "$tracking_branch_ct" != "0" ] && out+="-$tracking_branch_ct"

echo -e "$out"
git --git-dir="$dir/.git" --work-tree="$dir" status -s --column=row
