#!/bin/sh
# Compare number of commits ahead/behind between two git objects

dir="$1"
[ -z "$dir" ] && dir="$(pwd)"

left_obj="$2"
[ -z "$left_obj" ] && left_branch="master"

right_obj="$3"
[ -z "$right_obj" ] && right_obj="origin/master"

git --git-dir="$dir/.git" --work-tree="$dir" rev-list --left-right --count "$left_obj...$right_obj"
