#!/bin/sh
# Location n ip

addr="$(curl https://ifconfig.me 2>/dev/null)" || exit
flagemoji=$(grep "flag: " ~/.data/emoji \
  | grep "$(geoiplookup $addr \
  | sed 's/.*, //')" \
  | sed "s/flag: //;s/;.*//" \
  | cut -d " " -f "1"
)
echo "$flagemoji $addr"
