#!/bin/sh

mirrorlist_url="https://www.archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4"

curl -s "$mirrorlist_url" \
  | sed -e 's/^#Server/Server/' -e '/^#/d' \
  | rankmirrors -n 5 - \
  > /etc/pacman.d/mirrorlist
