#!/bin/sh
# Connects to wifi

nmcli radio wifi on

chosen=$(nmcli -t device wifi list \
  | cut -d ':' -f "2,5,7" \
  | sort -t$':' -k2 -n -r -u \
  | awk -F ":" '$1{print $1 " - " $3 " " $2}' \
  | dmenu -i -l 20 -fn Monospace-10 \
  | awk -F " - " '{print $1}'
)

[ -z "$chosen" ] && exit

password=$(dialog --no-cancel --passwordbox --insecure "Password" 10 60 3>&1 1>&2 2>&3 3>&1)

nmcli device wifi connect "$chosen" password "$password"

notify-send "Successfully connected to $chosen"
