#!/bin/sh
# Connects to wifi

nmcli radio wifi on

chosen=$(nmcli -t device wifi list \
  | cut -d ':' -f "2,5,7" \
  | sort -t$':' -k2 -n -r -u \
  | awk -F ":" '$1{print $1 " - " $3 " " $2}' \
  | fzf \
  | awk -F " - " '{print $1}'
)

[ -z "$chosen" ] && exit

nmcli device wifi connect "$chosen" --ask || exit 1

notify-send "Successfully connected to $chosen"
